services:
    cleverage_soap_process.task.request:
        class: CleverAge\SoapProcessBundle\Task\RequestTask
        public: false
        shared: false
        arguments:
            - '@monolog.logger'
            - '@cleverage_soap_process.registry.client'
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }
    CleverAge\SoapProcessBundle\Task\RequestTask:
        alias: cleverage_soap_process.task.request
        public: true
