services:
    cleverage_soap_process.transformer.request:
        class: CleverAge\SoapProcessBundle\Transformer\RequestTransformer
        public: false
        arguments:
            - '@cleverage_soap_process.registry.client'
        tags:
            - { name: cleverage.transformer }
            - { name: monolog.logger, channel: cleverage_process_transformer }
    CleverAge\SoapProcessBundle\Transformer\RequestTransformer:
        alias: cleverage_soap_process.transformer.request
